line-length = 100
target-version = "py312"

[lint]
preview = true
select = [
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "UP",
  "ANN",
  "ASYNC",
  "S",
  "FBT",
  "B",
  "A",
  "C4",
  "DTZ",
  "EM",
  "FA",
  "ISC",
  "LOG",
  "G",
  "PIE",
  "T20",
  "PT",
  "RSE",
  "RET",
  "SLOT",
  "SIM",
  "TC",
  "ARG",
  "PTH",
  "PL",
  "TRY",
  "FAST",
  "PERF",
  "FURB",
  "DOC",
  "RUF",
]
